#!/bin/sh
dist="/jails"
ezjail-admin create -f router -r $1 $1 0.0.0.0
/usr/sbin/jail -c vnet host.hostname=$1 name=$1 path=${dist}/$1 persist
mount -t devfs devfs ${dist}/$1/dev
mount_nullfs ${dist}/basejail ${dist}/$1/basejail
for pkg in `ls ${dist}/flavours/router/pkg`
do
  pkg -j $1 add /pkg/$pkg
done
echo $1 ' created.'
#
jail -r $1
umount ${dist}/$1/dev
umount ${dist}/$1/basejail
echo $1 ' unjailed.'
python3.7 router_init.py $1
